CREATE TABLE budgetfit.products (
  productsID int NOT NULL AUTO_INCREMENT,
  brand_name varchar(100) DEFAULT NULL,
  item_category varchar(100) DEFAULT NULL,
  item_name varchar(100) DEFAULT NULL,
  item_description text DEFAULT NULL,
  nf_ingredient_statement text DEFAULT NULL,
  nf_calories int DEFAULT NULL,
  nf_calories_from_fat int DEFAULT NULL,
  nf_total_fat float DEFAULT NULL,
  nf_saturated_fat float DEFAULT NULL,
  nf_trans_fatty_acid float DEFAULT NULL,
  nf_polyunsaturated_fat float DEFAULT NULL,
  nf_monounsaturated_fat float DEFAULT NULL,
  nf_cholesterol float DEFAULT NULL,
  nf_sodium float DEFAULT NULL,
  nf_total_carbohydrate float DEFAULT NULL,
  nf_dietary_fiber float DEFAULT NULL,
  nf_sugars float DEFAULT NULL,
  nf_protein float DEFAULT NULL,
  nf_vitamin_a_dv float DEFAULT NULL,
  nf_vitamin_c_dv float DEFAULT NULL,
  nf_calcium_dv float DEFAULT NULL,
  nf_iron_dv float DEFAULT NULL,
  nf_potassium float DEFAULT NULL,
  nf_servings_per_container int DEFAULT NULL,
  nf_serving_size_qty float DEFAULT NULL,
  nf_serving_size_unit varchar(100) DEFAULT NULL,
  nf_serving_weight_grams int DEFAULT NULL,
  metric_qty int DEFAULT NULL,
  metric_uom varchar(100) DEFAULT NULL,
  images_front_full_url varchar(255) DEFAULT NULL,
  item_price decimal(6, 2) DEFAULT NULL,
  modifiedDate datetime DEFAULT NULL,
  createdDate datetime DEFAULT NULL,
  PRIMARY KEY (productsID),
  UNIQUE INDEX id_UNIQUE (productsID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 112,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;