CREATE DEFINER=`root`@`%` PROCEDURE `setProducts`(
    IN brand_name VARCHAR(100),
    IN item_category VARCHAR(100),
    IN item_name VARCHAR(100),
    IN item_description TEXT,
    IN nf_ingredient_statement TEXT,
    IN nf_calories INT,
    IN nf_calories_from_fat INT,
    IN nf_total_fat FLOAT,
    IN nf_saturated_fat FLOAT,
    IN nf_trans_fatty_acid FLOAT,
    IN nf_polyunsaturated_fat FLOAT,
    IN nf_monounsaturated_fat FLOAT,
    IN nf_cholesterol FLOAT,
    IN nf_sodium FLOAT,
    IN nf_total_carbohydrate FLOAT,
    IN nf_dietary_fiber FLOAT,
    IN nf_sugars FLOAT,
    IN nf_protein FLOAT,
    IN nf_vitamin_a_dv FLOAT,
    IN nf_vitamin_c_dv FLOAT,
    IN nf_calcium_dv FLOAT,
    IN nf_iron_dv FLOAT,
    IN nf_potassium FLOAT,
    IN nf_servings_per_container INT,
    IN nf_serving_size_qty FLOAT,
    IN nf_serving_size_unit VARCHAR(100),
    IN nf_serving_weight_grams INT,
    IN metric_qty INT,
    IN metric_uom VARCHAR(100),
    IN images_front_full_url VARCHAR(255),
    IN item_price DECIMAL(6,2)
    )
BEGIN
    INSERT INTO 
    products (
        brand_name,
        item_category,
        item_name,
        item_description,
        nf_ingredient_statement,
        nf_calories,
        nf_calories_from_fat,
        nf_total_fat,
        nf_saturated_fat,
        nf_trans_fatty_acid,
        nf_polyunsaturated_fat,
        nf_monounsaturated_fat,
        nf_cholesterol,
        nf_sodium,
        nf_total_carbohydrate,
        nf_dietary_fiber,
        nf_sugars,
        nf_protein,
        nf_vitamin_a_dv,
        nf_vitamin_c_dv,
        nf_calcium_dv,
        nf_iron_dv,
        nf_potassium,
        nf_servings_per_container,
        nf_serving_size_qty,
        nf_serving_size_unit,
        nf_serving_weight_grams,
        metric_qty,
        metric_uom,
        images_front_full_url,
        item_price,
        modifiedDate,
        createdDate
        
)
VALUES (
        brand_name,
        item_category,
        item_name,
        item_description,
        nf_ingredient_statement,
        nf_calories,
        nf_calories_from_fat,
        nf_total_fat,
        nf_saturated_fat,
        nf_trans_fatty_acid,
        nf_polyunsaturated_fat,
        nf_monounsaturated_fat,
        nf_cholesterol,
        nf_sodium,
        nf_total_carbohydrate,
        nf_dietary_fiber,
        nf_sugars,
        nf_protein,
        nf_vitamin_a_dv,
        nf_vitamin_c_dv,
        nf_calcium_dv,
        nf_iron_dv,
        nf_potassium,
        nf_servings_per_container,
        nf_serving_size_qty,
        nf_serving_size_unit,
        nf_serving_weight_grams,
        metric_qty,
        metric_uom,
        images_front_full_url,
        item_price,
        NOW(),
        NOW()
);
END